### ISSUE TITLE
多应用模式下 /index.html 无法访问

### ISSUE THREAD

**Issue by zoujingli** [top-think/think-multi-app#11]
多应用模式下 /index.html , /admin.html 等带了后缀的不能访问。
在默认处理 pathinfo 的时候没有把 url 后缀去掉，导致生成的应用目录就变成了：
`app/index.html` 或 `app/admin.html`，正常应该是 `app/index` 或 `app/admin`

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/67740476-ea7e8a80-fa50-11e9-8217-01ff38efc256.png)
![image](https://user-images.githubusercontent.com/4349951/67740512-04b86880-fa51-11e9-804a-6621fd4e128e.png)

**Comment by zoujingli** [comment]
开启 app_express 可以正常访问

**Comment by liu21st** [comment]
已经修正
