### ISSUE TITLE
已使用的项目更新最新版，多应用无效

### ISSUE THREAD

**Issue by 4352570** [top-think/think-multi-app#15]
更新1.0.12
控制器不存在:app\controller\Index
恢复1.0.11 正常

**Comment by 4352570** [comment]
补充BUG情景
'with_event'       => false 
关闭事件时多应用失效，变为单应用

**Comment by yunwuxin** [comment]
事件必须启用  
事件机制很重要  最新的框架已经去除了这个配置了  不能关闭

**Comment by 4352570** [comment]
好的，找了半天代码，才发现是这个开关影响的

**Comment by lsswear** [comment]
tp6安装了多应用 但是build没有识别 系统也不识别多应用 看着向单应用 求解呀
