### ISSUE TITLE
think-swoole 多应用不支持

### ISSUE THREAD

**Issue by vatezj** [top-think/think-multi-app#21]
think-swoole 多应用不支持

**Comment by yunwuxin** [comment]
本来就不支持 
https://github.com/top-think/think-swoole/issues/121#issuecomment-597222363

**Comment by fywtat** [comment]
这就close了啊，代码上优化下可以支持吧。

**Comment by 54huige** [comment]
> 这就close了啊，代码上优化下可以支持吧。

你解决了吗 你用的什么方案解决的 单应用吗

**Comment by 54huige** [comment]
> 这就close了啊，代码上优化下可以支持吧。

我感觉是不是把多应用部署成单应用 一个一个跑才行吧

**Comment by muxik** [comment]
赶紧支持啊，

**Comment by liu21st** [comment]
多应用扩展其实用途不大 用新版的多模块就行了
