### ISSUE TITLE
多应用模式下，默认应用路由不生效

### ISSUE THREAD

**Issue by cs99619** [top-think/think-multi-app#31]
- 路由配置开启强制路由模式
- 路由文件app/home/route/route.php：
```
<?php

use think\facade\Route;

Route::get('/', 'Index');

Route::get('dd', 'Index/hd');

```
- app/home/controller/Index.php文件
```
<?php

declare(strict_types=1);

namespace app\home\controller;

class Index {
    public function index() {
        return '您好！这是一个[home]示例应用';
    }
    public function hd() {
        return '您好！这是一个[home hd]示例应用';
    }
}
```
访问URL，http://127.0.0.1:8000 时可以正常访问
但是访问http://127.0.0.1:8000/dd 时，提示路由未定义
![image](https://user-images.githubusercontent.com/12388126/116004819-217a3000-a637-11eb-9237-4ee79781f44c.png)

通过入口文件http://127.0.0.1:8000/home/dd访问正常
![image](https://user-images.githubusercontent.com/12388126/116004852-3ce53b00-a637-11eb-8aa7-5d6fc2cfae7c.png)

**Comment by liu21st** [comment]
多应用的路由都是独立的 没有所谓的默认应用的概念

**Comment by cs99619** [comment]
![image](https://user-images.githubusercontent.com/12388126/116686786-e84f1080-a9e6-11eb-9f2a-f5fb0d6fef3e.png)
如图所示：
config/app.php这个默认应用代表什么，在多应用下面，应该是这个生效的吧？
还是说上图所设定的默认应用只针对单应用模式？如果之针对单应用模式，为什么还出一个默认应用的设置？

劳动节Happly~
