### ISSUE TITLE
多应用?lang=en 无效果希望修复

### ISSUE THREAD

**Issue by muzidudu** [top-think/think-multi-app#32]
https://github.com/top-think/think-multi-app/blob/a997f2b54527020e8a39f071e29c6278f1fd0862/src/MultiApp.php#L242

这里有错误 望修正下
`$this->app->loadLangPack($this->app->lang->getLangSet());`

**Comment by 0377** [comment]
+1，希望尽快修复

**Comment by 0377** [comment]
`
app()->lang = new \think\Lang(\config('lang'));   

app()->lang->detect($request);   

app()->loadLangPack(Lang::getLangSet());    

`

在中间件里面重新实例化 app里面的lang可以实现语言切换

**Comment by liu21st** [comment]
在应用的中间件文件里面也加上 \think\middleware\LoadLangPack::class, 试下

**Comment by hulang** [comment]
@liu21st 大佬，既然更新了，发布下版本啊，不想用：dev版本额。
