### ISSUE TITLE
当前版本不兼容thinkphp8.1

### ISSUE THREAD

**Issue by FFCZ** [top-think/think-multi-app#48]
手痒不上心composer update到最新的thinkphp8.1，发现以下错误
vendor\topthink\think-multi-app\src\Url.php
151行
foreach() argument must be of type array|object, string given

**Comment by ken678** [comment]
目前多应用版本还未发布  同时建议其他一些更新php8.4的包 同步更新下 适配thinkphp8.1

**Comment by FFCZ** [comment]
临时加代码解决
if(is_string($binds)){
$binds = (array)$binds;
}

**Comment by ken678** [comment]
> 临时加代码解决 if(is_string($binds)){ $binds = (array)$binds; }

你装开发版就行 不用改
